### ISSUE TITLE
Error converting java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by ndarilek** [googleapis/java-texttospeech#38]
Using:

```
implementation('com.google.cloud:google-cloud-texttospeech:0.117.1-beta')
```

I'm getting the below error.

This library used to work fine. Unfortunately, it now fails after we converted the consuming service from web-based to GRPC-based. I'm wondering if perhaps something in the GRPC server implementation is stepping on the TTS GRPC client?

This also seems similar to googleapis/google-cloud-java#5810, which was pointed out to me when I reported this on Gitter. I'm running the absolute latest GRPC dependencies as well. I commented on that issue thinking that maybe it should be reopened, but there hasn't been a response in weeks so I'm trying with a fresh issue.

Here's the full stacktrace:

```
SEVERE: Error converting
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@69df22e5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@645a999a[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:707)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:657)
	at io.grpc.internal.FailingClientStream.start(FailingClientStream.java:54)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:290)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:190)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:394)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:695)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:315)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:287)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.texttospeech.v1.TextToSpeechClient.synthesizeSpeech(TextToSpeechClient.java:270)
	at com.google.cloud.texttospeech.v1.TextToSpeechClient.synthesizeSpeech(TextToSpeechClient.java:243)
	at io.scribe.converter.tts.TTSConverter.convert(tts.kt:257)
	at io.scribe.converter.ConverterImpl.createMp3IfNeeded(converter.kt:204)
	at io.scribe.converter.ConverterImpl.convert(converter.kt:255)
	at io.scribe.converter.ConverterGrpc$MethodHandlers.invoke(ConverterGrpc.java:279)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by codyoss** [comment]
Could you tell me what version of `com.google.api/gax` is being pulled into your dependencies? I believe the fix for the referenced issue was addressed there.

**Comment by ndarilek** [comment]
com.google.api:gax:1.50.1


Here is the output of ./gradlew dependencies:


https://gist.github.com/ndarilek/f14c386a2c50c1c49340c158e4adc9b9

**Comment by ndarilek** [comment]
I know it isn't directly related to this issue, but is there a Java equivalent of:

`gcloud auth application-default print-access-token`

I'm on a tight deadline, and to work around this bug, I'm using the Curl quickstart and Unirest to hand-craft the request. Unfortunately I need a bearer token, and I don't know how to get one other than by running the above shell command. So I'm doing that for now, but obviously since the library already has access to my credentials, I wonder if it has a faster way to spit out a bearer token I can use in the meantime.

Thanks.

**Comment by codyoss** [comment]
Questions for you:
JVM version?
OS?
How consistently does this happen, and how can I reproduce this?

**Comment by ndarilek** [comment]
Sorry, been a while and we rewrote this code to call the API by hand. 
BUt to answer your questions:


JVM version: Whatever ships in the Docker container 
openjdk:8u212-jre-slim-stretch

OS: Debian 9


Consistency: Always. Here's our current code, side-by-side with what we 
replaced. The commented-out code worked before we introduced our own 
GRPC server. I suspect a small GRPC server with a method that runs this 
code would trigger it for you:


```

// val ttsClient = TextToSpeechClient.create()
val total = ssmlChunks.size.toDouble()
val files = mutableListOf<String>()
for ((index, ssmlChunk) in ssmlChunks.withIndex()) {
try {
val mp3 = 
outputPath.resolveSibling("${outputPath.toFile().nameWithoutExtension}-${ssmlChunk.hash}.mp3")
if (Files.notExists(mp3)) {
// val input = SynthesisInput.newBuilder().setSsml(ssmlChunk.ssml).build()
// Check for supported languages
val voiceLanguage: String
if (ssmlChunk.language in this._supportedTtsLanguages) {
voiceLanguage = ssmlChunk.language
} else {
// The language is not supported by Google, use English by default
voiceLanguage = "en"
}
val voiceBuilder = 
VoiceSelectionParams.newBuilder().setLanguageCode(voiceLanguage)
when (gender) {
"male" -> {
voiceBuilder.setSsmlGender(SsmlVoiceGender.MALE)
}
"female" -> {
voiceBuilder.setSsmlGender(SsmlVoiceGender.FEMALE)
}
"neutral" -> {
voiceBuilder.setSsmlGender(SsmlVoiceGender.NEUTRAL)
}
}
/*val voice = voiceBuilder.build()
val audioConfig = AudioConfig.newBuilder()
.setAudioEncoding(AudioEncoding.OGG_OPUS)
.setSpeakingRate(speechRate)
.build()
val response = ttsClient.synthesizeSpeech(input, voice, audioConfig)
val audioContent = response.audioContent*/
val body = mutableMapOf<String, Any>()
val input = mutableMapOf<String, Any>()
input.put("ssml", ssmlChunk.ssml)
body.put("input", input)
val voice = mutableMapOf<String, Any>()
voice.put("languageCode", voiceLanguage)
voice.put("ssmlGender", gender.toUpperCase())
body.put("voice", voice)
val audioConfig = mutableMapOf<String, Any>()
audioConfig.put("audioEncoding", "OGG_OPUS")
audioConfig.put("speakingRate", speechRate)
body.put("audioConfig", audioConfig)
val exec = ProcessExecutor()
val args = listOf<String>("gcloud", "auth", "application-default", 
"print-access-token")
val token = exec.command(args)
.environment(System.getenv())
.readOutput(true)
.execute()
.outputUTF8()
val response = 
Unirest.post("https://texttospeech.googleapis.com/v1/text:synthesize")
.header("Authorization", "Bearer $token")
.body(body)
.asJson()
.getBody()
.getObject()
val audioContent = 
Base64.getDecoder().decode(response.getString("audioContent"))
val ogg = 
outputPath.resolveSibling("${outputPath.toFile().nameWithoutExtension}${ssmlChunk.hash}.ogg")
val fos = Files.newOutputStream(ogg, StandardOpenOption.CREATE)
try {
fos.write(audioContent)
} finally {
fos.close()
}
AudioConverter().convert(ogg, mp3, audioCodec="libmp3lame", 
bitrate="128K", sampleRate="44100", channels="2")
}
files.add(mp3.toString())
val newProgress = (index.toDouble() + 1) / total
progress(newProgress, ssmlChunk.hash, mp3)
} finally {
// ttsClient.close()
}
```
So pretty run-of-the-mill.
Thanks.

**Comment by codyoss** [comment]
Thanks for more info, we will look into this

**Comment by munkhuushmgl** [comment]
Hey @codyoss Is there any update concerning this issue?

**Comment by codyoss** [comment]
@munkhuushmgl I do not, but I have shifted gears away from the Java libraries many months ago.

**Comment by munkhuushmgl** [comment]
@ndarilek Are you still experiencing same issue?

**Comment by ndarilek** [comment]
No, moved on from that project a long time ago. Couldn't wait for a fix, 
so we manually called the API and gave up on the official Google bindings.
